server:
    port: 8089
spring:
    datasource:
      url: jdbc:dm://192.168.17.232:5236/LJBDDB?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
      username: LJBDDB
      password: LJBDDB123
      driver-class-name: dm.jdbc.driver.DmDriver

#        ConnectionTestQuery: SELECT 1
mybatis:
  # 指定sql映射文件位置
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.dc.entity
